version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: user-mongodb
    hostname: user-mongo
    ports:
      - '27017:27017' 
    volumes:
      - user_mongo_data:/data/db
    restart: unless-stopped
    networks:
      - common_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user-app
    hostname: user-app
    ports:
      - '8082:8082'
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://user-mongo:27017/UserDB  
      - JWT_SECRET=${JWT_SECRET:-your-very-secure-secret-key}
    volumes:
      - ./backend:/usr/src/app/backend
      - ./videos:/usr/src/app/videos
    restart: unless-stopped
    networks:
      - common_network
    command: ["node", "backend/app.js"]

volumes:
  user_mongo_data:

networks:
  common_network:
    driver: bridge
