version: "3.8"
services:
  nginx:
    build:
      context: ./nginx  # Make sure this path is correct
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - admin
      - user
    networks:
      - app-network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

  admin:
    build:
      context: ./Admin/project  # Correct path
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - app-network

  user:
    build:
      context: ./User/project  # Correct path
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    networks:
      - app-network

networks:
  app-network:
    external: true
