version: "3.8"
services:
  nginx:
    build:
      context: ./  # Path to the NGINX folder
      dockerfile: Dockerfile  # Dockerfile in the NGINX folder
    ports:
      - "80:80"
    depends_on:
      - admin
      - user
    networks:
      - app-network
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Ensure this file exists

  admin:
    build:
      context: ../Admin/project  # Path relative to the nginx directory
      dockerfile: Dockerfile
    ports:
      - "8081:8080"  # Change host port to avoid conflict
    networks:
      - app-network

  user:
    build:
      context: ../User/project  # Path relative to the nginx directory
      dockerfile: Dockerfile
    ports:
      - "8083:8082"  # Change host port to avoid conflict
    networks:
      - app-network

networks:
  app-network:
    external: true
