version: "3.8"
services:
  nginx:
    build:
      context: ./  # Path to the NGINX folder
      dockerfile: Dockerfile  # Dockerfile in the NGINX folder
    ports:
      - "80:80"
      - "8083:8082"  # Change the port here for user service to avoid conflict
    depends_on:
      - admin
      - user
    networks:
      - app-network
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Ensure this file exists

  admin:
    build:
      context: ../Admin/project  # Path relative to the nginx directory
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - app-network

  user:
    build:
      context: ../User/project  # Path relative to the nginx directory
      dockerfile: Dockerfile
    ports:
      - "8082:8082"  # Keep the same port for the user service
    networks:
      - app-network

networks:
  app-network:
    external: true
