version: "3.8"
services:
  nginx:
    build:
      context: ./nginx  # Path to the NGINX folder
      dockerfile: Dockerfile  # Dockerfile in the NGINX folder
    ports:
      - "80:80"
    depends_on:
      - admin
      - user
    networks:
      - app-network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf  # Ensure this file exists

  admin:
    build:
      context: ../Admin/project  # Path relative to the nginx directory
      dockerfile: Dockerfile  # Make sure the Dockerfile is present in the Admin folder
    ports:
      - "8080:8080"
    networks:
      - app-network

  user:
    build:
      context: ../User/project  # Path relative to the nginx directory
      dockerfile: Dockerfile  # Make sure the Dockerfile is present in the User folder
    ports:
      - "8082:8082"
    networks:
      - app-network

networks:
  app-network:
    external: true
