version: "3.8"
services:
  admin:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - MONGO_URL=mongodb://mongo:27017/AdminDB
    depends_on:
      mongo:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s
    networks:
      - app-network

  mongo:
    image: mongo:latest
    container_name: admin-mongo
    ports:
      - "27017:27017"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "echo 'db.runCommand({ ping: 1 })' | mongosh localhost:27017 --quiet"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  app-network:
    external: true
