version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: admin-mongodb
    hostname: admin-mongo
    ports:
      - '27019:27017'
    volumes:
      - admin_mongo_data:/data/db
    restart: always
    networks:
      - common_network
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.runCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 3

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: admin-app
    hostname: admin-app
    ports:
      - '8080:8080'
    depends_on:
      mongo:
        condition: service_healthy  # Ensure mongo is healthy
    environment:
      - MONGO_URI=mongodb://admin-mongo:27017/AdminDB
      - JWT_SECRET=${JWT_SECRET:-your-very-secure-secret-key}
      - GCS_BUCKET_NAME=${GCS_BUCKET_NAME:-nivenmoviebucket}
      - GCP_PROJECT_ID=${GCP_PROJECT_ID:-your-google-cloud-project-id}
    volumes:
      - ./backend:/usr/src/app/backend
    restart: always
    networks:
      - common_network
    command: ["node", "backend/app.js"]

volumes:
  admin_mongo_data:

networks:
  common_network:
    driver: bridge
