name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.22.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Admin Service
        run: |
          cd Admin/project
          docker-compose -f admin-docker-compose.yaml -p admin build
          docker images # Verify the built images
          docker tag admin-admin:latest 2481553/admin-service:latest
          docker push 2481553/admin-service:latest

      - name: Build and Push User Service
        run: |
          cd User/project
          docker-compose -f user-docker-compose.yaml -p user build
          docker images # Verify the built images
          docker tag user_user:latest 2481553/user-service:latest
          docker push 2481553/user-service:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy Admin Service
        run: |
          cd Admin/project
          docker-compose -f admin-docker-compose.yaml -p admin down
          docker-compose -f admin-docker-compose.yaml -p admin up --build -d

      - name: Deploy User Service
        run: |
          cd User/project
          docker-compose -f user-docker-compose.yaml -p user down
          docker-compose -f user-docker-compose.yaml -p user up --build -d
