name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.22.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Build and Push Admin Service
        run: |
          cd Admin/project
          for i in {1..3}; do npm install --no-optional && break || sleep 5; done
          docker-compose -f admin-docker-compose.yaml -p admin build
          docker tag admin-admin:latest 2481553/admin-service:latest
          docker push 2481553/admin-service:latest

      - name: Build and Push User Service
        run: |
          cd User/project
          for i in {1..3}; do npm install --no-optional && break || sleep 5; done
          docker-compose -f user-docker-compose.yaml -p user build
          docker tag user-user:latest 2481553/user-service:latest
          docker push 2481553/user-service:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 54.91.154.173 >> ~/.ssh/known_hosts

      - name: Deploy to Cloud9
        run: |
          ssh ec2-user@54.91.154.173 << 'EOF'
          docker-compose -f Admin/project/admin-docker-compose.yaml -p admin down || true
          docker-compose -f User/project/user-docker-compose.yaml -p user down || true
          docker network rm app-network || true
          docker network create app-network || true
          cd Admin/project
          docker-compose -f admin-docker-compose.yaml -p admin up --build --force-recreate -d
          cd ../../User/project
          docker-compose -f user-docker-compose.yaml -p user up --build --force-recreate -d
          docker network inspect app-network
          docker ps
          EOF
